10 REM MAKES THE START SCREEN LOOK LIKE A COMMODORE 64
20 IF YOU WANT, OU COULD DO "BG 4" TOO, BUT I PREFER
30 REM TO LET COOL-RETRO-TERM DO MY COLOR SCHEME.
40 BOLD ON
50 CLEAR
60 CENTER "**** BREAKAWAY BASIC  0.4 ****"
70 CENTER FRE(), "BYTES FREE"
80 PRINT CHR$(10);
90 PROMPT CHR$(10) + "READY." + CHR$(10)
