#include "main.h"

void UnTokenize(unsigned char* tokens, FILE* where) {
	size_t i;
	for (i = 0; i < INPUT_BUFFER_SIZE; i++) {
		switch(tokens[i]) {
			case ABS: fprintf(where, " ABS("); break;
			case ALL: fprintf(where, " ALL"); break;
			case AND: fprintf(where, " AND"); break;
			case AS: fprintf(where, " AS"); break;
			case ASC: fprintf(where, " ASC("); break;
			case ATN: fprintf(where, " ATN("); break;
			case AUTO: fprintf(where, " AUTO"); break;
			case BACKSLASH: fprintf(where, "\\"); break;
			case BEEP: fprintf(where, " BEEP"); break;
			case BIN: fprintf(where, " BIN$("); break;
			case BOLD: fprintf(where, " BOLD"); break;
			case CDBL: fprintf(where, " CDBL("); break;
			case CD: fprintf(where, " CHDIR"); break;
			case CHAIN: fprintf(where, " CHAIN"); break;
			case CHR: fprintf(where, " CHR$("); break;
			case CINT: fprintf(where, " CINT("); break;
			case CLEAR: fprintf(where, " CLEAR"); break;
			case CLOSE: fprintf(where, " CLOSE"); break;
			case CLS: fprintf(where, " CLS"); break;
			case COLON: fprintf(where, ":"); break;
			case COLOR: fprintf(where, " COLOR"); break;
			case COMMA: fprintf(where, ","); break;
			case COMMON: fprintf(where, " COMMON"); break;
			case CONT: fprintf(where, " CONT"); break;
			case COS: fprintf(where, " COS("); break;
			case CSNG: fprintf(where, " CSNG("); break;
			case CVD: fprintf(where, " CVD("); break;
			case CVI: fprintf(where, " CVI("); break;
			case CVL: fprintf(where, " CVL("); break;
			case CVS: fprintf(where, " CVS("); break;
			case CSRLIN: fprintf(where, " CSRLIN"); break;
			case CURSES: fprintf(where, " CURSES"); break;
			case DASH: fprintf(where, "-"); break;
			case DATA: fprintf(where, " DATA"); break;
			case DATE: fprintf(where, " DATE$"); break;
			case DBL: fprintf(where, " DBL"); break;
			case DEF: fprintf(where, " DEF"); break;
			case DELETE: fprintf(where, " DELETE"); break;
			case DIM: fprintf(where, " DIM"); break;
			case DOUBLE_STAR: fprintf(where, "**"); break;
			case EDIT: fprintf(where, " EDIT"); break;
			case ELSE: fprintf(where, " ELSE"); break;
			case END: fprintf(where, " END"); break;
			case ENVIRONS: fprintf(where, " ENVIRON$("); break;
			case ENVIRON: fprintf(where, " ENVIRON"); break;
			case EQUALS: fprintf(where, "="); break;
			case ERASE: fprintf(where, " ERASE"); break;
			case EQV: fprintf(where, " EQV"); break;
			case ERL: fprintf(where, " ERL"); break;
			case ERR: fprintf(where, " ERR"); break;
			case ERROR: fprintf(where, " ERROR"); break;
			case EXIT: return;
			case EXP: fprintf(where, " EXP("); break;
			case FIELD: fprintf(where, " FIELD"); break;
			case FILES: fprintf(where, " FILES"); break;
			case FIX: fprintf(where, " FIX("); break;
			case FN: fprintf(where, " FN"); break;
			case FOR: fprintf(where, " FOR"); break;
			case FREEFILE: fprintf(where, " FREEFILE"); break;
			case FREE: fprintf(where, " FREE"); break;
			case GET: fprintf(where, " GET"); break;
			case GOSUB: fprintf(where, " GOSUB"); break;
			case GOTO: fprintf(where, " GOTO"); break;
			case GREATER_THAN_OR_EQUAL: fprintf(where, ">="); break;
			case GREATER_THAN: fprintf(where, ">"); break;
			case HASH: fprintf(where, "#"); break;
			case HAT: fprintf(where, "^"); break;
			case HEX: fprintf(where, " HEX$("); break;
			case IF: fprintf(where, " IF"); break;
			case IMP: fprintf(where, " IMP"); break;
			case INKEY: fprintf(where, " INKEY$"); break;
			case INP: fprintf(where, " INP("); break;
			case INPUT: fprintf(where, " INPUT"); break;
			case INPUTS: fprintf(where, " INPUT$("); break;
			case INSTR: fprintf(where, " INSTR("); break;
			case INTERPRET: fprintf(where, " INTERPRET"); break;
			case INT: fprintf(where, " INT("); break;
			case INT2: fprintf(where, " INT"); break;
			case KILL: fprintf(where, " KILL"); break;
			case LCASE: fprintf(where, "LCASE$("); break;
			case LEFT: fprintf(where, " LEFT$("); break;
			case LEFT_BRACKET: fprintf(where, "["); break;
			case LEFT_PAREN: fprintf(where, "("); break;
			case LEN: fprintf(where, " LEN"); break;
			case LESS_THAN_OR_EQUAL: fprintf(where, "<="); break;
			case LESS_THAN: fprintf(where, "<"); break;
			case LET: fprintf(where, " LET"); break;
			case LINE: fprintf(where, " LINE"); break;
			case LIST: fprintf(where, " LIST"); break;
			case LLIST: fprintf(where, " LLIST"); break;
			case LOAD: fprintf(where, " LOAD"); break;
			case LOC: fprintf(where, " LOC("); break;
			case LOCATE: fprintf(where, " LOCATE"); break;
			case LOF: fprintf(where, " LOF("); break;
			case LOG: fprintf(where, " LOG("); break;
			case LPOS: fprintf(where, " LPOS("); break;
			case LPRINT: fprintf(where, " LPRINT"); break;
			case LSET: fprintf(where, " LSET"); break;
			case LTRIM: fprintf(where, " LTRIM"); break;
			case MERGE: fprintf(where, " MERGE"); break;
			case MID: fprintf(where, " MID$("); break;
			case MKD: fprintf(where, " MKD$("); break;
			case MKDIR: fprintf(where, " MKDIR"); break;
			case MKI: fprintf(where, " MKI$("); break;
			case MKL: fprintf(where, " MKL$("); break;
			case MKS: fprintf(where, " MKS$("); break;
			case MOD: fprintf(where, " MOD"); break;
			case NAME: fprintf(where, " NAME"); break;
			case NEW: fprintf(where, " NEW"); break;
			case NEXT: fprintf(where, " NEXT"); break;
			case NOT: fprintf(where, " NOT"); break;
			case NOT_EQUAL: fprintf(where, " ><"); break;
			case BASIC_NULL: fprintf(where, " NULL"); break;
			case OCT: fprintf(where, " OCT$("); break;
			case OFF: fprintf(where, " OFF"); break;
			case ON: fprintf(where, " ON"); break;
			case OUT: fprintf(where, " OUT"); break;
			case OPEN: fprintf(where, " OPEN"); break;
			case OPTION: fprintf(where, " OPTION"); break;
			case OR: fprintf(where, " OR"); break;
			case PEEK: fprintf(where, " PEEK("); break;
			case PLUS: fprintf(where, "+"); break;
			case POKE: fprintf(where, " POKE"); break;
			case POS: fprintf(where, " POS"); break;
			case PRINT: fprintf(where, " PRINT"); break;
			case PUT: fprintf(where, " PUT"); break;
			case RANDOMIZE: fprintf(where, " RANDOMIZE"); break;
			case READ: fprintf(where, " READ"); break;
			case RENUMBER: fprintf(where, " RENUMBER"); break;
			case RESTORE: fprintf(where, " RESTORE"); break;
			case RESUME: fprintf(where, " RESUME"); break;
			case RETURN: fprintf(where, " RETURN"); break;
			case REM: fprintf(where, " REM%s", (char*)&tokens[1]); return;
			case RIGHT: fprintf(where, " RIGHT$("); break;
			case RIGHT_BRACKET: fprintf(where, "]"); break;
			case RIGHT_PAREN: fprintf(where, ")"); break;
			case RMDIR: fprintf(where, " RMDIR"); break;
			case RND: fprintf(where, " RND("); break;
			case RSET: fprintf(where, " RSET"); break;
			case RTRIM: fprintf(where, " RTRIM$("); break;
			case RUN: fprintf(where, " RUN"); break;
			case SAVE: fprintf(where, " SAVE"); break;
			case SEG: fprintf(where, " SEG"); break;
			case SEMICOLON: fprintf(where, ";"); break;
			case SGN: fprintf(where, " SGN("); break;
			case SIN: fprintf(where, " SIN("); break;
			case SLASH: fprintf(where, "/"); break;
			case SLEEP: fprintf(where, " SLEEP"); break;
			case SNG: fprintf(where, " SNG"); break;
			case SPACE: fprintf(where, " SPACE$("); break;
			case SPC: fprintf(where, " SPC("); break;
			case SQR: fprintf(where, " SQR("); break;
			case STAR: fprintf(where, "*"); break;
			case STEP: fprintf(where, " STEP"); break;
			case STOP: fprintf(where, " STOP"); break;
			case STR: fprintf(where, " STR$("); break;
			case STRINGF: fprintf(where, " STRING$("); break;
			case SWAP: fprintf(where, " SWAP"); break;
			case SYSTEM: fprintf(where, " SYSTEM"); break;
			case TAB: fprintf(where, " TAB("); break;
			case TAN: fprintf(where, " TAN("); break;
			case THEN: fprintf(where, " THEN"); break;
			case TIME: fprintf(where, " TIME$"); break;
			case TIMER: fprintf(where, " TIMER"); break;
			case TO: fprintf(where, " TO"); break;
			case TROFF: fprintf(where, " TROFF"); break;
			case TRON: fprintf(where, " TRON"); break;
			case UCASE: fprintf(where, " UCASE"); break;
			case USING: fprintf(where, " USING"); break;
			case VAL: fprintf(where, " VAL("); break;
			case VARPTR: fprintf(where, " VARPTR("); break;
			case VARS: fprintf(where, " VARS"); break;
			case WAIT: fprintf(where, " WAIT"); break;
			case WEND: fprintf(where, " WEND"); break;
			case WHILE: fprintf(where, " WHILE"); break;
			case WIDTH: fprintf(where, " WIDTH"); break;
			case WRITE: fprintf(where, " WRITE"); break;
			case XOR: fprintf(where, " XOR"); break;
			case NUMBER:
				i++;
				fprintf(where, " ");
				while(i < INPUT_BUFFER_SIZE && tokens[i] != NUMBER) {
					fprintf(where, "%c", tokens[i]);
					i++;
				}
				break;
			case VARIABLE:
			case UNKNOWN:
			case STRING_LITERAL:
				/* These are weirdos - handle these later :) */
				fprintf(where, "{weirdo}"); break;
			case NONE:
				/* 0, like a NULL terminator, end of line */
				return;
			default:
				fprintf(where, "\r\nTO-DO: un-tokenize %d\r\n", tokens[i]);
				break;
		}
	}
}
